name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  test-core:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      # - name: "Set environmental variables"
      #   run: |
      #       echo "SVSHI_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.5.0
        with:
          distribution: zulu
          java-version: 17

      - name: Install CVC4
        run: |
          sudo apt-get install -y cvc4 

      - name: Install Stainless
        run: |
          git clone https://github.com/epfl-lara/stainless.git
          cd stainless
          sbt universal:stage
          
      - name: Build and Test
        run: cd src/ && ../stainless/frontends/dotty/target/universal/stage/bin/stainless-dotty VerifiedRegexMatcher.scala  ListUtils.scala VerifiedNFA.scala VerifiedFunLexer.scala -Dparallel=3 --config-file=stainless.conf

  fail_if_pull_request_is_draft:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-18.04
    steps:
    - name: Fails in order to indicate that pull request needs to be marked as ready to review and unit tests workflow needs to pass.
      run: exit 1